export const attentionItems = [
  {
    count: 8,
    title: "Candidates need review",
    detail: "Three have been waiting longer than your 24-hour review target.",
    action: "Open review queue",
    tone: "attention" as const,
    icon: "review",
  },
  {
    count: 3,
    title: "Interviews to score",
    detail: "Scorecards are due before tomorrow’s hiring review.",
    action: "Complete scorecards",
    tone: "brand" as const,
    icon: "interview",
  },
  {
    count: 2,
    title: "Automation exceptions",
    detail: "Candidate notifications paused after delivery failures.",
    action: "Resolve exceptions",
    tone: "danger" as const,
    icon: "exception",
  },
];

export const requisitions = [
  {
    role: "Assistant Professor, Computer Science",
    code: "CS-042",
    location: "Islamabad · On campus",
    owner: "Ayesha Khan",
    candidates: 31,
    waiting: 5,
    stage: "Interviewing",
    tone: "brand" as const,
    next: "Review 5 candidates",
  },
  {
    role: "Lecturer, Data Science",
    code: "DS-018",
    location: "Lahore · On campus",
    owner: "Samira Iqbal",
    candidates: 18,
    waiting: 2,
    stage: "SLA at risk",
    tone: "attention" as const,
    next: "Triage shortlist",
  },
  {
    role: "Visiting Faculty, Cybersecurity",
    code: "CYB-011",
    location: "Karachi · Visiting",
    owner: "Hamza Ali",
    candidates: 24,
    waiting: 0,
    stage: "Screening",
    tone: "neutral" as const,
    next: "View pipeline",
  },
  {
    role: "Research Associate, AI",
    code: "AI-027",
    location: "Islamabad · Hybrid",
    owner: "Priya Shah",
    candidates: 12,
    waiting: 1,
    stage: "Approval required",
    tone: "approval" as const,
    next: "Review offer",
  },
];

export const activity = [
  {
    initials: "AL",
    candidate: "Hira Ahmed",
    action: "completed an applied interview",
    role: "Assistant Professor, Computer Science",
    time: "12 min ago",
    next: "Score interview",
  },
  {
    initials: "DR",
    candidate: "Daniyal Raza",
    action: "advanced to panel interview",
    role: "Lecturer, Data Science",
    time: "38 min ago",
    next: "Schedule panel",
  },
  {
    initials: "NO",
    candidate: "Nadia Omar",
    action: "submitted requested evidence",
    role: "Visiting Faculty, Cybersecurity",
    time: "1 hr ago",
    next: "Review evidence",
  },
  {
    initials: "MW",
    candidate: "Mahnoor Waheed",
    action: "accepted an interview invitation",
    role: "Research Associate, AI",
    time: "2 hrs ago",
    next: "View interview",
  },
];
